TARGET = xk-audio-316-mc.xn
APP_NAME =
XCC_FLAGS = -g -DADAT_TX_USE_SHARED_BUFF
USED_MODULES = lib_adat lib_sw_pll

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
