TARGET = xk-audio-316-mc.xn
APP_NAME =
XCC_FLAGS = -O3 -g -D ADAT_REF=100
USED_MODULES = lib_adat

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
